return {
['Алмазный фазан']={name='Алмазный фазан', nameprod='Мясо фазана', tm=6,  buyagro=5, sell=150, tp='Мясо птиц', tp1='Животные' , location='Заповедник',    corall='Вольер для фазанов', yncorall=2},
['Аляскинский лось']={name='Аляскинский лось', nameprod='Мясо лося', tm=900,  buyagro=8, sell=780, tp='Мясо', tp1='Животные' ,   levelagro=25,  corall='Загон для лосей', yncorall=2 , buyagro1=5, levelagro1=38},
['Американский бизон']={name='Американский бизон', nameprod='Мясо бизона', tm=180,  buyagro=5, sell=108, tp='Мясо', tp1='Животные' ,   levelagro=24,  corall='Загон для бизонов', yncorall=2 , buyagro1=2, levelagro1=33},
['Американский бобер']={name='Американский бобер', nameprod='Мех бобра', tm=14, buy=11000, buyagro=4, sell=180, tp='Мех', tp1='Животные' ,  level=24, levelagro=15,  corall='Хатка бобра', yncorall=2},
['Американский лось']={name='Американский лось', nameprod='Мясо лося', tm=1260,  buyagro=6, sell=780, tp='Мясо', tp1='Животные' ,   levelagro=23,  corall='Загон для лосей', yncorall=2 , buyagro1=4, levelagro1=31},
['Американский хорек']={name='Американский хорек', nameprod='Мех хорька', tm=16,  buyagro=3, sell=400, tp='Мех', tp1='Животные' ,   levelagro=36,  corall='Вольер для хорьков', yncorall=2},
['Аризонский перепел']={name='Аризонский перепел', nameprod='Перепелиное яйцо', tm=120,  buyagro=6, sell=75, tp='Яйца', tp1='Животные' ,   levelagro=58,   yncorall=0},
['Архар']={name='Архар', nameprod='Нежная баранина', tm=360,  buyagro=4, sell=91, tp='Мясо', tp1='Животные' ,   levelagro=15,  corall='Загон для архара', yncorall=2},
['Африканский буйвол']={name='Африканский буйвол', nameprod='Говядина', tm=300,  buyagro=6, sell=330, tp='Мясо', tp1='Животные' ,   levelagro=27, res='Пшеница' ,  yncorall=0 , buyagro1=4, levelagro1=47},
['Баран-муфлон']={name='Баран-муфлон', nameprod='Баранина', tm=900, buy=25000,  sell=190, tp='Мясо', tp1='Животные' ,  level=18,   corall='Загон для баранов', yncorall=2},
['Баргузинский соболь']={name='Баргузинский соболь', nameprod='Мех соболя', tm=9,  buyagro=4, sell=200, tp='Мех', tp1='Животные' ,   levelagro=44,  corall='Загон для соболей', yncorall=2 , buyagro1=7, levelagro1=34},
['Белая индейка']={name='Белая индейка', nameprod='Мясо индюка', tm=4,  buyagro=5, sell=45, tp='Мясо птиц', tp1='Животные' ,   levelagro=42,  corall='Индюшатник', yncorall=2},
['Белобрюхий глухарь']={name='Белобрюхий глухарь', nameprod='Мясо глухаря', tm=10,  buyagro=4, sell=910, tp='Мясо птиц', tp1='Животные' ,   levelagro=32,  corall=''},
['Белогрудая цесарка']={name='Белогрудая цесарка', nameprod='Яйцо цесарки', tm=1,  buyagro=3, sell=112, tp='Яйца', tp1='Животные' ,   levelagro=37, res='Чечевица' ,  yncorall=0 , buyagro1=5, levelagro1=14},
['Белый баран']={name='Белый баран', nameprod='Баранина', tm=660,  buyagro=3, sell=190, tp='Мясо', tp1='Животные' ,   levelagro=15,  corall='Загон для баранов', yncorall=2},
['Бык Герефолд']={name='Бык Герефолд', nameprod='Говядина', tm=840, buy=10000, buyagro=4, sell=330, tp='Мясо', tp1='Животные' ,  level=24, levelagro=12,  corall='Загон для быков', yncorall=2},
['Глухарь']={name='Глухарь', nameprod='Мясо глухаря', tm=11,  buyagro=3, sell=910, tp='Мясо птиц', tp1='Животные' ,   levelagro=40,  corall='Вольер для глухарей', yncorall=1 , buyagro1=5, levelagro1=24},
['Грифовая цесарка']={name='Грифовая цесарка', nameprod='Яйцо цесарки', tm=3, buy=25000, buyagro=3, sell=112, tp='Яйца', tp1='Животные' ,  level=28, levelagro=14, res='Чечевица' ,  yncorall=0},
['Гусь']={name='Гусь', nameprod='Мясо гуся', tm=12, buy=4500, buyagro=3, sell=60, tp='Мясо птиц', tp1='Животные' ,  level=28, levelagro=16,  corall='Гусятник', yncorall=2},
['Дальневосточная косуля']={name='Дальневосточная косуля', nameprod='Оленина', tm=120,  buyagro=6, sell=132, tp='Мясо', tp1='Животные' ,   levelagro=48,  corall='Загон для косуль', yncorall=2},
['Домашний бык']={name='Домашний бык', nameprod='Говядина', tm=240,  buyagro=8, sell=330, tp='Мясо', tp1='Животные' ,   levelagro=24,  corall='Загон для быков', yncorall=2 , buyagro1=5, levelagro1=37},
['Европейская косуля']={name='Европейская косуля', nameprod='Оленина', tm=600, buy=19000,  sell=132, tp='Мясо', tp1='Животные' ,  level=22,   corall='Загон для косуль', yncorall=2},
['Европейский бизон']={name='Европейский бизон', nameprod='Мясо бизона', tm=300, buy=13000, buyagro=4, sell=108, tp='Мясо', tp1='Животные' ,  level=30, levelagro=22,  corall='Загон для бизонов', yncorall=2},
['Европейский бобр']={name='Европейский бобр', nameprod='Мех бобра', tm=4,  buyagro=3, sell=180, tp='Мех', tp1='Животные' ,   levelagro=30,  corall='Хатка бобра', yncorall=2 , buyagro1=6, levelagro1=20},
['Зааненская коза']={name='Зааненская коза', nameprod='Козье молоко', tm=1,  buyagro=3, sell=88, tp='Производство молока', tp1='Животные' ,   levelagro=15, res='Брокколи' ,  yncorall=1},
['Заяц-беляк']={name='Заяц-беляк', nameprod='Зайчатина', tm=300,  buyagro=4, sell=106, tp='Мясо', tp1='Животные' ,   levelagro=18,  corall='Загон для зайцев', yncorall=2 , buyagro1=2, levelagro1=31},
['Заяц-русак']={name='Заяц-русак', nameprod='Зайчатина', tm=600, buy=25000, buyagro=3, sell=106, tp='Мясо', tp1='Животные' ,  level=28, levelagro=18,  corall='Загон для зайцев', yncorall=2},
['Золотой фазан']={name='Золотой фазан', nameprod='Мясо фазана', tm=14, buy=25000, buyagro=5, sell=150, tp='Мясо птиц', tp1='Животные' , location='Заповедник',    corall='Вольер для фазанов', yncorall=2},
['Индюк']={name='Индюк', nameprod='Мясо индюка', tm=6, buy=22000,  sell=45, tp='Мясо птиц', tp1='Животные' ,  level=17,   corall='Индюшатник', yncorall=2},
['Калан азиатский']={name='Калан азиатский', nameprod='Мех калана', tm=20, buy=19000, buyagro=3, sell=260, tp='Мех', tp1='Животные' ,  level=22, levelagro=15,  corall='Загон для каланов', yncorall=2},
['Калан калифорнийский']={name='Калан калифорнийский', nameprod='Мех калана', tm=12,  buyagro=4, sell=260, tp='Мех', tp1='Животные' ,   levelagro=27,  corall='Загон для каланов', yncorall=2 , buyagro1=6, levelagro1=15},
['Калан камчатский']={name='Калан камчатский', nameprod='Мех калана', tm=6,  buyagro=6, sell=260, tp='Мех', tp1='Животные' ,   levelagro=38,  corall='Загон для каланов', yncorall=2},
['Калан северный']={name='Калан северный', nameprod='Мех калана', tm=8,  buyagro=5, sell=260, tp='Мех', tp1='Животные' ,   levelagro=34,  corall='Загон для каланов', yncorall=2 , buyagro1=8, levelagro1=15},
['Калифорнийский перепел']={name='Калифорнийский перепел', nameprod='Перепелиное яйцо', tm=240,  buyagro=3, sell=75, tp='Яйца', tp1='Животные' ,   levelagro=32,  corall='Вольер для перепелов', yncorall=2},
['Каменная куница']={name='Каменная куница', nameprod='Мех куницы', tm=11,  buyagro=5, sell=210, tp='Мех', tp1='Животные' ,   levelagro=12,  corall='Загон для куниц', yncorall=2 , buyagro1=3, levelagro1=24},
['Каменный глухарь']={name='Каменный глухарь', nameprod='Мясо глухаря', tm=20, buy=70000,  sell=910, tp='Мясо птиц', tp1='Животные' ,  level=37,   corall=''},
['Камчатский соболь']={name='Камчатский соболь', nameprod='Мех соболя', tm=6,  buyagro=6, sell=200, tp='Мех', tp1='Животные' ,   levelagro=48,   yncorall=1},
['Канадский бобр']={name='Канадский бобр', nameprod='Мех бобра', tm=6,  buyagro=2, sell=180, tp='Мех', tp1='Животные' ,   levelagro=28,  corall='Хатка бобра', yncorall=2 , buyagro1=5, levelagro1=18},
['Канадский лось']={name='Канадский лось', nameprod='Мясо лося', tm=720,  buyagro=6, sell=780, tp='Мясо', tp1='Животные' ,   levelagro=42,   yncorall=2},
['Коричневый баран']={name='Коричневый баран', nameprod='Баранина', tm=1200, buy=10000,  sell=190, tp='Мясо', tp1='Животные' ,  level=8,   corall='Загон для баранов', yncorall=2},
['Корова Аирширская']={name='Корова Аирширская', nameprod='Молоко', tm=40,  buyagro=3, sell=25, tp='Производство молока', tp1='Животные' ,   levelagro=1, res='Клевер' ,  yncorall=1},
['Корова Голштинская']={name='Корова Голштинская', nameprod='Молоко', tm=1, buy=2500,  sell=25, tp='Производство молока', tp1='Животные' ,  level=4,  res='Клевер' ,  yncorall=1},
['Корова Холмогорская']={name='Корова Холмогорская', nameprod='Молоко', tm=20,  buyagro=5, sell=25, tp='Производство молока', tp1='Животные' ,   levelagro=11, res='Клевер' ,  yncorall=1},
['Косуля']={name='Косуля', nameprod='Оленина', tm=360, buy=23000, buyagro=3, sell=132, tp='Мясо', tp1='Животные' ,  level=32, levelagro=25,  corall='Загон для косуль', yncorall=2},
['Красноярский соболь']={name='Красноярский соболь', nameprod='Мех соболя', tm=20, buy=18000, buyagro=4, sell=200, tp='Мех', tp1='Животные' ,  level=35, levelagro=26,  corall='Загон для соболей', yncorall=2},
['Куница-рыболов']={name='Куница-рыболов', nameprod='Мех куницы', tm=21, buy=16000, buyagro=3, sell=210, tp='Мех', tp1='Животные' ,  level=19, levelagro=12,  corall='Загон для куниц', yncorall=2},
['Курица бройлер']={name='Курица бройлер', nameprod='Курятина', tm=24, buy=20000,  sell=300, tp='Мясо птиц', tp1='Животные' ,  level=13,   corall=''},
['Курица Доркинг']={name='Курица Доркинг', nameprod='Курятина', tm=16,  buyagro=2, sell=300, tp='Мясо птиц', tp1='Животные' ,   levelagro=22,  corall=''},
['Курица Кохинкинг']={name='Курица Кохинкинг', nameprod='Курятина', tm=8,  buyagro=6, sell=300, tp='Мясо птиц', tp1='Животные' ,   levelagro=54,  corall=''},
['Курица']={name='Курица', nameprod='Яйцо', tm=2, buy=700,  sell=102, tp='Яйца', tp1='Животные' ,    res='Кукуруза' , corall='Курятник', yncorall=1},
['Кучинская курица']={name='Кучинская курица', nameprod='Яйцо', tm=5,  buyagro=3, sell=178, tp='Яйца', tp1='Животные' ,   levelagro=35, res='Подсолнух' ,  yncorall=0},
['Лесная куница']={name='Лесная куница', nameprod='Мех куницы', tm=6,  buyagro=6, sell=210, tp='Мех', tp1='Животные' ,   levelagro=42,  corall='Загон для куниц', yncorall=2},
['Лесной бизон']={name='Лесной бизон', nameprod='Мясо бизона', tm=120,  buyagro=7, sell=108, tp='Мясо', tp1='Животные' ,   levelagro=27,  corall='Загон для бизонов', yncorall=2 , buyagro1=3, levelagro1=40},
['Лесной хорек']={name='Лесной хорек', nameprod='Мех хорька', tm=10,  buyagro=5, sell=400, tp='Мех', tp1='Животные' ,   levelagro=45,  corall='Вольер для хорьков', yncorall=2},
['Маньчжурский заяц']={name='Маньчжурский заяц', nameprod='Зайчатина', tm=480, buy=40000,  sell=106, tp='Мясо', tp1='Животные' ,  level=33,    yncorall=0},
['Нилгирийская куница']={name='Нилгирийская куница', nameprod='Мех куницы', tm=8,  buyagro=4, sell=210, tp='Мех', tp1='Животные' ,   levelagro=29,  corall='Загон для куниц', yncorall=2 , buyagro1=7, levelagro1=12},
['Новозеландский кролик']={name='Новозеландский кролик', nameprod='Крольчатина', tm=720,  buyagro=3, sell=750, tp='Мясо', tp1='Животные' ,   levelagro=41, res='Морковь' ,  yncorall=0},
['Нубийская коза']={name='Нубийская коза', nameprod='Козье молоко', tm=60,  buyagro=5, sell=88, tp='Производство молока', tp1='Животные' ,   levelagro=26, res='Брокколи' ,  yncorall=1},

['Перепел']={name='Перепел', nameprod='Перепелиное яйцо', tm=720, buy=16000,  sell=75, tp='Яйца', tp1='Животные' ,  level=14,   corall='Вольер для перепелов', yncorall=2},
['Перепел-арлекин']={name='Перепел-арлекин', nameprod='Перепелиное яйцо', tm=180,  buyagro=4, sell=75, tp='Яйца', tp1='Животные' ,   levelagro=47,   yncorall=0},
['Рябой гусь']={name='Рябой гусь', nameprod='Мясо гуся', tm=2,  buyagro=4, sell=60, tp='Мясо птиц', tp1='Животные' ,   levelagro=39,  corall='Гусятник', yncorall=2 , buyagro1=6, levelagro1=25},
['Рябчик']={name='Рябчик', nameprod='Мясо рябчика', tm=26,  buyagro=3, sell=730, tp='Мясо птиц', tp1='Животные' ,   levelagro=18,  corall='Вольер для рябчиков', yncorall=1 , buyagro1=1, levelagro1=31},
['Сибирская косуля']={name='Сибирская косуля', nameprod='Оленина', tm=240,  buyagro=7, sell=132, tp='Мясо', tp1='Животные' ,   levelagro=25,  corall='Загон для косуль', yncorall=2 , buyagro1=3, levelagro1=34},
['Сибирский соболь']={name='Сибирский соболь', nameprod='Мех соболя', tm=13,  buyagro=3, sell=200, tp='Мех', tp1='Животные' ,   levelagro=39,  corall='Загон для соболей', yncorall=2 , buyagro1=5, levelagro1=30},
['Снежный баран']={name='Снежный баран', nameprod='Нежная баранина', tm=420, buy=14000,  sell=91, tp='Мясо', tp1='Животные' ,  level=26,   corall='Загон для архара', yncorall=2},
['Степной хорек']={name='Степной хорек', nameprod='Мех хорька', tm=24, buy=40000,  sell=400, tp='Мех', tp1='Животные' ,  level=27,   corall='Вольер для хорьков', yncorall=2},
['Страус']={name='Страус', nameprod='Страусиное яйцо', tm=2, buy=1500,  sell=178, tp='Яйца', tp1='Животные' ,  level=14,  res='Капуста' , corall='Загон для страусов', yncorall=1},
['Суматрийский заяц']={name='Суматрийский заяц', nameprod='Зайчатина', tm=240,  buyagro=5, sell=106, tp='Мясо', tp1='Животные' ,   levelagro=18,  corall='Загон для зайцев', yncorall=2 , buyagro1=3, levelagro1=37},
['Тоггенбургская коза']={name='Тоггенбургская коза', nameprod='Козье молоко', tm=120, buy=31000,  sell=88, tp='Производство молока', tp1='Животные' ,   levelagro=26, res='Брокколи' ,  yncorall=1},
['Тутовый шелкопряд']={name='Тутовый шелкопряд', nameprod='Шелковая нить', tm=1440,  buyagro=1, sell=830, tp='Другое', tp1='Животные' ,     corall='Тутовая роща', yncorall=1},
['Уссурийский лось']={name='Уссурийский лось', nameprod='Мясо лося', tm=2880, buy=11000, buyagro=4, sell=780, tp='Мясо', tp1='Животные' ,  level=28, levelagro=20,  corall='Загон для лосей', yncorall=2},
['Утка']={name='Утка', nameprod='Яйцо', tm=1,5, buy=3000,  sell=102, tp='Яйца', tp1='Животные' ,  level=11,  res='Подсолнух' , corall='Пруд для уток', yncorall=1},
['Фазан Свайно']={name='Фазан Свайно', nameprod='Мясо фазана', tm=8,  buyagro=3, sell=150, tp='Мясо птиц', tp1='Животные' , location='Заповедник',    corall='Вольер для фазанов', yncorall=2},
['Фиолетовый Страус']={name='Фиолетовый Страус', nameprod='Страусиное яйцо', tm=2,  buyagro=3, sell=178, tp='Яйца', tp1='Животные' ,   levelagro=12, res='Капуста' , corall='Загон для страусов', yncorall=1},
['Хохлатая цесарка']={name='Хохлатая цесарка', nameprod='Яйцо цесарки', tm=2,  buyagro=2, sell=112, tp='Яйца', tp1='Животные' ,   levelagro=31, res='Чечевица' ,  yncorall=0 , buyagro1=4, levelagro1=14},
['Цигайская овца']={name='Цигайская овца', nameprod='Овечье молоко', tm=22, buy=160000,  sell=600, tp='Производство молока', tp1='Животные' ,   levelagro=41, res='Кукуруза' ,  yncorall=1},
['Черная косуля']={name='Черная косуля', nameprod='Оленина', tm=180,  buyagro=8, sell=132, tp='Мясо', tp1='Животные' ,   levelagro=25,  corall='Загон для косуль', yncorall=2 , buyagro1=5, levelagro1=37},
['Черная утка']={name='Черная утка', nameprod='Яйцо', tm=1,5,  buyagro=1, sell=102, tp='Яйца', tp1='Животные' ,    res='Подсолнух' , corall='Пруд для уток', yncorall=1},
['Черноголовая овца']={name='Черноголовая овца', nameprod='Овечье молоко', tm=18,  buyagro=5, sell=600, tp='Производство молока', tp1='Животные' ,   levelagro=28, res='Кукуруза' ,  yncorall=1},
['Черный Ангус']={name='Черный Ангус', nameprod='Говядина', tm=480,  buyagro=5, sell=330, tp='Мясо', tp1='Животные' ,   levelagro=19,  corall='Загон для быков', yncorall=2 , buyagro1=3, levelagro1=30},
['Черный баран']={name='Черный баран', nameprod='Баранина', tm=480,  buyagro=5, sell=190, tp='Мясо', tp1='Животные' ,   levelagro=32,  corall='Загон для баранов', yncorall=2},
['Черный гусь']={name='Черный гусь', nameprod='Мясо гуся', tm=6,  buyagro=3, sell=60, tp='Мясо птиц', tp1='Животные' ,   levelagro=29,  corall='Гусятник', yncorall=2 , buyagro1=5, levelagro1=18},
['Черный Страус']={name='Черный Страус', nameprod='Страусиное яйцо', tm=2,  buyagro=2, sell=178, tp='Яйца', tp1='Животные' ,   levelagro=13, res='Капуста' , corall='Загон для страусов', yncorall=1},

['Белорусская свинья']={name='Белорусская свинья', nameprod='Свинина', tm=240,  buyagro=5, sell=144, tp='Мясо', tp1='Животные' ,   levelagro=49, res='Ячмень' ,  yncorall=0},
['Гемпширская свинья']={name='Гемпширская свинья', nameprod='Свинина', tm=240,  buyagro=5, sell=144, tp='Мясо', tp1='Животные' ,   levelagro=35,  corall='Загон для свиней', yncorall=2},
['Свинья']={name='Свинья', nameprod='Свинина', tm=960, buy=8000,  sell=144, tp='Мясо', tp1='Животные' ,  level=6,   corall='Загон для свиней', yncorall=2},
['Черная свинья']={name='Черная свинья', nameprod='Свинина', tm=540,  buyagro=3, sell=144, tp='Мясо', tp1='Животные' ,   levelagro=21,  corall='Загон для свиней', yncorall=2},

['Белая куропатка']={name='Белая куропатка', nameprod='Мясо куропатки', tm=32, buy=30000, buyagro=3, sell=220, tp='Мясо птиц', tp1='Животные' ,  level=28, levelagro=19,  corall='Вольер для куропаток', yncorall=2},
['Горная куропатка']={name='Горная куропатка', nameprod='Мясо куропатки', tm=12,  buyagro=4, sell=220, tp='Мясо птиц', tp1='Животные' ,   levelagro=35,  corall='Вольер для куропаток', yncorall=2 , buyagro1=7, levelagro1=19},
['Серая куропатка']={name='Серая куропатка', nameprod='Мясо куропатки', tm=19,  buyagro=3, sell=220, tp='Мясо птиц', tp1='Животные' ,   levelagro=31,  corall='Вольер для куропаток', yncorall=2 , buyagro1=5, levelagro1=19},

['Пчелы']={name='Пчелы', nameprod='Мед', tm=0.5, buy=2000,  sell=5, tp='Другие животные', tp1='Животные' ,  level=3,  res='Клевер' ,  yncorall=0},
['Кубанские пчелы']={name='Кубанские пчелы', nameprod='Мед', tm=0.33,  buyagro=3, sell=5, tp='Другие животные', tp1='Животные' ,   levelagro=9, res='Клевер' ,  yncorall=0},


['Павлин']={name='Павлин', nameprod='Перо', tm=2, buy=9000,  sell=200, tp='Другие животные', tp1='Животные' ,  level=12,  res='Белый виноград' , corall='Загон для павлинов', yncorall=1},
['Белый павлин']={name='Белый павлин', nameprod='Перо', tm=2,  buyagro=2, sell=200, tp='Другие животные', tp1='Животные' ,   levelagro=18, res='Белый виноград' , corall='Загон для павлинов', yncorall=1},
['Фиолетовый павлин']={name='Фиолетовый павлин', nameprod='Перо', tm=2,  buyagro=1, sell=200, tp='Другие животные', tp1='Животные' ,   levelagro=15, res='Белый виноград' , corall='Загон для павлинов', yncorall=1},

['Американская лиса']={name='Американская лиса', nameprod='Мех лисы', tm=23, buy=13000, buyagro=4, sell=245, tp='Мех', tp1='Животные' ,  level=29, levelagro=21,  corall='Загон для лисиц', yncorall=2},
['Платиновая лисица']={name='Платиновая лисица', nameprod='Мех лисы', tm=5,  buyagro=5, sell=245, tp='Мех', tp1='Животные' ,   levelagro=38,  corall='Загон для лисиц', yncorall=2},
['Рыжая лиса']={name='Рыжая лиса', nameprod='Мех лисы', tm=11,  buyagro=2, sell=245, tp='Мех', tp1='Животные' ,   levelagro=32,  corall='Загон для лисиц', yncorall=2 , buyagro1=5, levelagro1=23},
['Тибетская лиса']={name='Тибетская лиса', nameprod='Мех лисы', tm=7,  buyagro=3, sell=245, tp='Мех', tp1='Животные' ,   levelagro=36,  corall='Загон для лисиц', yncorall=2 , buyagro1=7, levelagro1=29},

['Кашемировая коза']={name='Кашемировая коза', nameprod='Кашемировый пух', tm=24,  buyagro=3, sell=960, tp='Шерсть', tp1='Животные' ,   levelagro=42, res='Цветная капуста' ,  yncorall=0},
['Китайская коза']={name='Китайская коза', nameprod='Кашемировый пух', tm=18,  buyagro=5, sell=960, tp='Шерсть', tp1='Животные' ,   levelagro=37, res='Цветная капуста' ,  yncorall=0},

['Альпака Сури']={name='Альпака Сури', nameprod='Шерсть альпаки', tm=1320, buy=50000,  sell=800, tp='Шерсть', tp1='Животные' ,  level=39,  res='Свекла' ,  yncorall=0},
['Альпака Уакайа']={name='Альпака Уакайа', nameprod='Шерсть альпаки', tm=960,  buyagro=4, sell=800, tp='Шерсть', tp1='Животные' ,   levelagro=27, res='Свекла' ,  yncorall=0},


['Ангорский кролик']={name='Ангорский кролик', nameprod='Ангорская шерсть', tm=1.33, buy=13000,  sell=94, tp='Шерсть', tp1='Животные' ,  level=15,  res='Морковь' ,  yncorall=0},

['Дикий вепрь']={name='Дикий вепрь', nameprod='Свинина', tm=180, buy=59000, buyagro=8, sell=144, tp='Мясо', tp1='Животные' , location='Высокогорье',     },

['Дюгонь']={name='Дюгонь', nameprod='Мясо дюгоня', tm=1320, buy=150000, buyagro=9, sell=900, tp='Мясо', tp1='Животные' , location='Коралловый атолл',     },
['Электрический скат']={name='Электрический скат', nameprod='Мяср ската', tm=1200, buy=80000, buyagro=5, sell=600, tp='Мясо', tp1='Животные' , location='Коралловый атолл',     },
['Чепрачный тапир']={name='Чепрачный тапир', nameprod='Мясо тапира', tm=960, buy=65000, buyagro=2, sell=400, tp='Мясо', tp1='Животные' , location='Коралловый атолл',     },
['Морская корова']={name='Морская корова', nameprod='Мясо морской коровы', tm=1440, buy=120000, buyagro=7, sell=1000, tp='Мясо', tp1='Животные' , location='Коралловый атолл',   res='Водоросли комбу' ,  },
['Толсторог']={name='Толсторог', nameprod='Баранина', tm=180, buy=45000, buyagro=3, sell=190, tp='Мясо', tp1='Животные' , location='Коралловый атолл',     },
['Зеленая черепаха']={name='Зеленая черепаха', nameprod='Мясо черепахи', tm=1440, buy=79000, buyagro=5, sell=600, tp='Мясо', tp1='Животные' , location='Коралловый атолл',     },
['Красные лобстеры']={name='Красные лобстеры', nameprod='Мясо лобстера', tm=720, buy=110000, buyagro=6, sell=650, tp='Мясо', tp1='Животные' , location='Коралловый атолл',     },
['Осьминот']={name='Осьминот', nameprod='Щупальца осьминога', tm=960, buy=148000, buyagro=7, sell=700, tp='Мясо', tp1='Животные' , location='Коралловый атолл',     },
['Скат манта']={name='Скат манта', nameprod='Мяср ската', tm=960, buy=100000, buyagro=7, sell=600, tp='Мясо', tp1='Животные' , location='Коралловый атолл',     },
['Синяя морская звезда']={name='Синяя морская звезда', nameprod='Морская звезда', tm=1080, buy=78000, buyagro=4, sell=680, tp='Мясо', tp1='Животные' , location='Коралловый атолл',     },
['Центральноамериканский тапир']={name='Центральноамериканский тапир', nameprod='Мясо тапира', tm=840, buy=75000, buyagro=3, sell=400, tp='Мясо', tp1='Животные' , location='Коралловый атолл',     },
['Желтоголовая черепха']={name='Желтоголовая черепха', nameprod='Мясо черепахи', tm=1320, buy=85000, buyagro=5, sell=600, tp='Мясо', tp1='Животные' , location='Коралловый атолл',     },
['Малек сельди']={name='Малек сельди', nameprod='Сельдь', tm=3240, buy=500, sell=2400, tp='Другие животные', tp1='Животные' , res='Корм для рыбы' , corall='Бассейн для рыбы', yncorall=1     },
['Малек сайры']={name='Малек сайры', nameprod='Сайра', tm=1800, buy=1500, sell=2700, tp='Другие животные', tp1='Животные' , res='Корм для рыбы' , corall='Бассейн для рыбы', yncorall=1     },
['Малек горбуши']={name='Малек горбуши', nameprod='Горбуша', tm=1080, buy=2600, sell=3360, tp='Другие животные', tp1='Животные' , res='Корм для рыбы' , corall='Бассейн для рыбы', yncorall=1     },
['Малек сардины']={name='Малек сардины', nameprod='Сардина', tm=2160, buy=1100, sell=2500, tp='Другие животные', tp1='Животные' , res='Корм для рыбы' , corall='Бассейн для рыбы', yncorall=1     },
['Малек тунца']={name='Малек тунца', nameprod='Тунец', tm=1440, buy=2000, sell=2980, tp='Другие животные', tp1='Животные' , res='Корм для рыбы' , corall='Бассейн для рыбы', yncorall=1     },
['Малек скумбрии']={name='Малек скумбрии', nameprod='Скумбрия', tm=2700, buy=800, sell=2450, tp='Другие животные', tp1='Животные' , res='Корм для рыбы' , corall='Бассейн для рыбы', yncorall=1     },
['Малек кальмара']={name='Малек кальмара', nameprod='Кальмар', tm=1260, buy=2300, sell=3150, tp='Другие животные', tp1='Животные' , res='Корм для рыбы' , corall='Бассейн для рыбы', yncorall=1     },
['Малек краба']={name='Малек краба', nameprod='Краб', tm=900, buy=3200, sell=3600, tp='Другие животные', tp1='Животные' , res='Корм для рыбы' , corall='Бассейн для рыбы', yncorall=1     },
['Малек плотвы']={name='Малек плотвы', nameprod='Плотва', tm=720, buy=100, sell=310, tp='Другие животные', tp1='Животные' , res='Корм для рыбы' , corall='Бассейн для рыбы', yncorall=1     },



}

