return {
{name='Арка "Вальс цветов"', buy=27000,  level=22, buyagro=3, levelagro=8, sell=0, tp='Заборы', del='270', exper=32},
{name='Арка "Весенние цветы"', buy=0,  level=0, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=0},
{name='Арка дракона', buy=0,  level=0, buyagro=2, levelagro=39, sell=0, tp='Заборы', del='', exper=0},
{name='Бамбуковый забор', buy=15000,  level=22, buyagro=1, levelagro=16, sell=0, tp='Заборы', del='', exper=4},
{name='Белый забор', buy=150,  level=4, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=1},
{name='Бирюзовый забор', buy=250,  level=18, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=1},
{name='Вафельный забор', buy=9000,  level=12, buyagro=1, levelagro=7, sell=0, tp='Заборы', del='', exper=15},
{name='Весенний забор', buy=10000,  level=30, buyagro=1, levelagro=10, sell=0, tp='Заборы', del='', exper=4},
{name='Весенняя арка', buy=50000,  level=32, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=30},
{name='Весенняя калитка', buy=40000,  level=30, buyagro=2, levelagro=10, sell=0, tp='Заборы', del='', exper=8},
{name='Ворота', buy=4000,  level=17, buyagro=1, levelagro=6, sell=0, tp='Заборы', del='', exper=4},
{name='Ворота "Алые листья"', buy=30000,  level=34, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=30},
{name='Ворота "Арко"', buy=30000,  level=35, buyagro=2, levelagro=15, sell=0, tp='Заборы', del='500', exper=20},
{name='Ворота "Версаль"', buy=0,  level=0, buyagro=3, levelagro=5, sell=0, tp='Заборы', del='', exper=0},
{name='Ворота из бамбука', buy=25000,  level=28, buyagro=3, levelagro=16, sell=0, tp='Заборы', del='', exper=4},
{name='Ворота ранчо', buy=3500,  level=14, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=1},
{name='Ворота с воробьями', buy=0,  level=0, buyagro=3, levelagro=20, sell=0, tp='Заборы', del='', exper=0},
{name='Галактические ворота', buy=0,  level=0, buyagro=1, levelagro=33, sell=0, tp='Заборы', del='', exper=0},
{name='Деревенский забор', buy=2000,  level=27, buyagro=1, levelagro=16, sell=0, tp='Заборы', del='', exper=1},
{name='Деревянные ворота', buy=10000,  level=10, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=18},
{name='Деревянный забор', buy=125,  level=1, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=1},
{name='Жёлтый забор', buy=200,  level=12, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=1},
{name='Живая изгородь (желтый)', buy=400,  level=8, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=4},
{name='Живая изгородь (красный)', buy=0,  level=0, buyagro=1, levelagro=9, sell=0, tp='Заборы', del='', exper=4},
{name='Забор', buy=700,  level=15, buyagro=1, levelagro=2, sell=0, tp='Заборы', del='', exper=4},
{name='Забор "Весенний"', buy=0,  level=0, buyagro=3, levelagro=8, sell=0, tp='Заборы', del='', exper=0},
{name='Забор "Гортензия"', buy=0,  level=0, buyagro=3, levelagro=8, sell=0, tp='Заборы', del='', exper=0},
{name='Забор "Романья"', buy=15000,  level=35, buyagro=1, levelagro=15, sell=0, tp='Заборы', del='', exper=10},
{name='Забор "Фиалка"', buy=0,  level=0, buyagro=3, levelagro=8, sell=0, tp='Заборы', del='', exper=0},
{name='Забор-насест', buy=30000,  level=20, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=0},
{name='Зелёный забор', buy=175,  level=6, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=1},
{name='Изгородь «Алые листья»', buy=17000,  level=34, buyagro=2, levelagro=15, sell=0, tp='Заборы', del='', exper=0},
{name='Изгородь «Монпарнас»', buy=15000,  level=25, buyagro=1, levelagro=5, sell=0, tp='Заборы', del='', exper=0},
{name='Изящная калитка', buy=22000,  level=25, buyagro=2, levelagro=18, sell=0, tp='Заборы', del='', exper=0},
{name='Изящный забор', buy=10000,  level=25, buyagro=2, levelagro=10, sell=0, tp='Заборы', del='', exper=0},
{name='Императорские ворота', buy=0,  level=0, buyagro=2, levelagro=39, sell=0, tp='Заборы', del='', exper=0},
{name='Инопланетная изгородь', buy=22000,  level=33, buyagro=1, levelagro=13, sell=0, tp='Заборы', del='', exper=0},
{name='Каменные ворота', buy=15000,  level=12, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='150', exper=23},
{name='Каменный забор', buy=6000,  level=12, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='60', exper=12},
{name='Кованые ворота', buy=18000,  level=37, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=0},
{name='Колючая проволока', buy=800,  level=10, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='50', exper=7},
{name='Коты на заборе', buy=0,  level=0, buyagro=3, levelagro=6, sell=0, tp='Заборы', del='', exper=4},
{name='Кристальная изгородь', buy=10000,  level=22, buyagro=1, levelagro=12, sell=0, tp='Заборы', del='', exper=0},
{name='Малая живая изгородь', buy=375,  level=5, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=3},
{name='Металлический забор', buy=500,  level=25, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=5},
{name='Музыкальная изгородь', buy=10000,  level=20, buyagro=1, levelagro=4, sell=0, tp='Заборы', del='', exper=0},
{name='Музыкальные ворота', buy=0,  level=0, buyagro=3, levelagro=5, sell=0, tp='Заборы', del='', exper=0},
{name='Ограда', buy=700,  level=31, buyagro=1, levelagro=5, sell=0, tp='Заборы', del='', exper=0},
{name='Ограда «Дачная»', buy=0,  level=0, buyagro=1, levelagro=20, sell=0, tp='Заборы', del='100', exper=30},
{name='Паписад', buy=0,  level=0, buyagro=2, levelagro=1, sell=0, tp='Заборы', del='100', exper=20},
{name='Плетеная арка', buy=0,  level=0, buyagro=1, levelagro=40, sell=0, tp='Заборы', del='', exper=0},
{name='Позолоченная изгородь', buy=23000,  level=37, buyagro=1, levelagro=17, sell=0, tp='Заборы', del='', exper=0},
{name='Ппетень', buy=15000,  level=15, buyagro=1, levelagro=15, sell=0, tp='Заборы', del='', exper=0},
{name='Праздничный забор', buy=20000,  level=31, buyagro=1, levelagro=11, sell=0, tp='Заборы', del='', exper=0},
{name='Радужные ворота', buy=0,  level=0, buyagro=2, levelagro=16, sell=0, tp='Заборы', del='', exper=0},
{name='Радужный забор', buy=11000,  level=26, buyagro=1, levelagro=16, sell=0, tp='Заборы', del='', exper=0},
{name='Резная китайская изгородь', buy=15000,  level=39, buyagro=1, levelagro=19, sell=0, tp='Заборы', del='', exper=0},
{name='Резной забор', buy=750,  level=21, buyagro=1, levelagro=11, sell=0, tp='Заборы', del='', exper=4},
{name='Резные ворога', buy=2500,  level=24, buyagro=1, levelagro=16, sell=0, tp='Заборы', del='', exper=4},
{name='Романские ворота', buy=4000,  level=21, buyagro=1, levelagro=11, sell=0, tp='Заборы', del='', exper=4},
{name='Романский забор', buy=1000,  level=18, buyagro=1, levelagro=7, sell=0, tp='Заборы', del='', exper=4},
{name='Рубиновый забор', buy=500,  level=33, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=1},
{name='Русский забор', buy=2000,  level=30, buyagro=1, levelagro=21, sell=0, tp='Заборы', del='', exper=0},
{name='Сказочная изгородь', buy=12000,  level=34, buyagro=1, levelagro=14, sell=0, tp='Заборы', del='', exper=0},
{name='Сказочная калитка', buy=38000,  level=34, buyagro=2, levelagro=14, sell=0, tp='Заборы', del='', exper=0},
{name='Сосновые ворота', buy=0,  level=0, buyagro=3, levelagro=6, sell=0, tp='Заборы', del='', exper=0},
{name='Сосновый забор', buy=10000,  level=25, buyagro=1, levelagro=6, sell=0, tp='Заборы', del='', exper=0},
{name='Триумфальная арка', buy=0,  level=0, buyagro=2, levelagro=21, sell=0, tp='Заборы', del='', exper=0},
{name='Тыквенная ограда', buy=18000,  level=28, buyagro=1, levelagro=8, sell=0, tp='Заборы', del='', exper=0},
{name='Цветочная арка', buy=800,  level=6, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=0},
{name='Цветочный забор', buy=0,  level=0, buyagro=3, levelagro=8, sell=0, tp='Заборы', del='', exper=0},
{name='Цветущая изгородь', buy=10000,  level=21, buyagro=1, levelagro=11, sell=0, tp='Заборы', del='', exper=0},
{name='Цветущие ворота', buy=0,  level=0, buyagro=2, levelagro=11, sell=0, tp='Заборы', del='', exper=0},
{name='Чёрный забор', buy=350,  level=26, buyagro=0, levelagro=0, sell=0, tp='Заборы', del='', exper=1},
{name='Японская изгородь', buy=20000,  level=19, buyagro=1, levelagro=19, sell=0, tp='Заборы', del='', exper=0},
{name='Японские ворота', buy=40000,  level=19, buyagro=2, levelagro=19, sell=0, tp='Заборы', del='', exper=0},
{name='Вафельная плитка', buy=0,  level=0, buyagro=2, levelagro=7, sell=0, tp='Плитки', del='', exper=0},
{name='Дворцовая брусчатка', buy=0,  level=0, buyagro=3, levelagro=17, sell=0, tp='Плитки', del='', exper=0},
{name='Желтая дорожка', buy=0,  level=0, buyagro=700, levelagro=14, sell=0, tp='Плитки', del='', exper=0},
{name='Заснеженная земля', buy=10000,  level=20, buyagro=1, levelagro=10, sell=0, tp='Плитки', del='', exper=0},
{name='Каменная дорожка', buy=0,  level=0, buyagro=500, levelagro=10, sell=0, tp='Плитки', del='', exper=0},
{name='Парковая брусчатка', buy=0,  level=0, buyagro=2, levelagro=17, sell=0, tp='Плитки', del='', exper=0},
{name='Первоцветы', buy=10000,  level=31, buyagro=1, levelagro=11, sell=0, tp='Плитки', del='', exper=0},
{name='Плитка «Китайский фарфор»', buy=10000,  level=35, buyagro=2, levelagro=15, sell=0, tp='Плитки', del='', exper=0},
{name='Плитка «Музыка осени»', buy=12000,  level=28, buyagro=4, levelagro=6, sell=0, tp='Плитки', del='', exper=0},
{name='Плитка «Роза ветров»', buy=12000,  level=28, buyagro=4, levelagro=6, sell=0, tp='Плитки', del='', exper=0},
{name='Римская плитка', buy=0,  level=0, buyagro=3, levelagro=7, sell=0, tp='Плитки', del='', exper=0},
{name='Розовая плитка', buy=0,  level=0, buyagro=2, levelagro=7, sell=0, tp='Плитки', del='', exper=0},
{name='Садовая брусчатка', buy=5000,  level=17, buyagro=1, levelagro=17, sell=0, tp='Плитки', del='', exper=0},
{name='Терракотовая плитка', buy=5000,  level=7, buyagro=1, levelagro=7, sell=0, tp='Плитки', del='', exper=0},
{name='Футуристическая плитка', buy=18000,  level=34, buyagro=1, levelagro=14, sell=0, tp='Плитки', del='', exper=0},
{name='Цветочная дорожка', buy=0,  level=0, buyagro=3, levelagro=8, sell=0, tp='Плитки', del='', exper=0},
{name='Песчаная дорожка', buy=300,  level=0, buyagro=0, levelagro=0, sell=0, tp='Плитки', del='', exper=0},
{name='Плитка "Инь-Янь"', buy=10000,  level=25, buyagro=3, levelagro=5, sell=0, tp='Плитки', del='', exper=0},
{name='Белая водяная лилия', buy=0,  level=0, buyagro=2, levelagro=24, sell=0, tp='Водные', del='', exper=0},
{name='Весёлые стрекозы', buy=0,  level=0, buyagro=3, levelagro=44, sell=0, tp='Водные', del='', exper=0},
{name='Водный ирис', buy=0,  level=0, buyagro=2, levelagro=32, sell=0, tp='Водные', del='', exper=0},
{name='Гондола', buy=34000,  level=31, buyagro=2, levelagro=14, sell=0, tp='Водные', del='', exper=0},
{name='Домик для уточек', buy=0,  level=0, buyagro=3, levelagro=30, sell=0, tp='Водные', del='', exper=0},
{name='Желтая водяная лилия', buy=11000,  level=12, buyagro=1, levelagro=1, sell=0, tp='Водные', del='', exper=0},
{name='Клумба «Цветущее каноэ»', buy=0,  level=0, buyagro=3, levelagro=42, sell=0, tp='Водные', del='', exper=0},
{name='Кувшинка ', buy=61000,  level=39, buyagro=1, levelagro=1, sell=0, tp='Водные', del='', exper=0},
{name='Лягушка на кувшинке', buy=0,  level=0, buyagro=2, levelagro=42, sell=0, tp='Водные', del='', exper=0},
{name='Морской коралл', buy=0,  level=0, buyagro=8, levelagro=1, sell=0, tp='Водные', del='', exper=0},
{name='Речной камень', buy=36000,  level=24, buyagro=1, levelagro=1, sell=0, tp='Водные', del='', exper=0},
{name='Речной камыш ', buy=27000,  level=18, buyagro=1, levelagro=1, sell=0, tp='Водные', del='', exper=0},
{name='Речной фонарик', buy=42000,  level=45, buyagro=3, levelagro=27, sell=0, tp='Водные', del='', exper=0},
{name='Розовая водяная лилия', buy=32000,  level=24, buyagro=3, levelagro=1, sell=0, tp='Водные', del='', exper=0},
{name='Фонтан «Речной»', buy=0,  level=0, buyagro=3, levelagro=46, sell=0, tp='Водные', del='', exper=0},

}

