return {
['Адонис']={name='Адонис', tm=9, buy=95, sell=116, tp='Цветы', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=1250, level=0},
['Азалия']={name='Азалия', tm=5, buy=55, sell=68, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=180, level=24},
['Акантолимон']={name='Акантолимон', tm=11, buy=120, sell=0, tp='Цветы', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=270, level=0},
['Аконит']={name='Аконит', tm=13, buy=0, sell=220, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=60, level=27, vip=1},
['Альпийский мак']={name='Альпийский мак', tm=9, buy=60, sell=0, tp='Цветы', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=330, level=0},
['Альстремерия']={name='Альстремерия', tm=6, buy=170, sell=265, tp='Цветы', tp1='Семена' , agronom={{name='Лилия', c=1},{name='Орхидея', c=1},{name='Автоматизация', c=15},},create={{name='Лилия', c=5},{name='Орхидея', c=5},{name='Определитель кислотности', c=3},},createtm=4, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=100, level=14},
['Ананас']={name='Ананас', tm=22, buy=115, sell=140, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=215, level=14},
['Арахис']={name='Арахис', tm=11, buy=155, sell=170, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=395, level=7},
['Арбуз']={name='Арбуз', tm=12, buy=130, sell=143, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=3380, level=39},
['Арбузный редис']={name='Арбузный редис', tm=12, buy=265, sell=411, tp='Фрукты', tp1='Семена' , agronom={{name='Арбуз', c=1},{name='Редис', c=1},{name='Автоматизация', c=5},},create={{name='Арбуз', c=30},{name='Редис', c=30},{name='Монеты', c=30000},},createtm=16, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=3861, level=39},
['Артишок']={name='Артишок', tm=12, buy=90, sell=110, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=630, level=21},
['Астра']={name='Астра', tm=8, buy=65, sell=80, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=180, level=26},
['Атлантический огурец']={name='Атлантический огурец', tm=11, buy=1650, sell=1826, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=12000, level=20},
['Базилик']={name='Базилик', tm=5, buy=50, sell=56, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=360, level=9},
['Баклажан']={name='Баклажан', tm=6, buy=16, sell=23, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=21, level=2},
['Бамия']={name='Бамия', tm=22, buy=100, sell=155, tp='Овощи', tp1='Семена' ,  location='Тропический остров', diamond=0, platinum=0, gold=0, silver=0, bronze=130, level=0},
['Барвинок']={name='Барвинок', tm=5, buy=42, sell=54, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=80, level=11},
['Бартзелла']={name='Бартзелла', tm=12, buy=90, sell=190, tp='Цветы', tp1='Семена' , agronom={{name='Пион', c=1},{name='Тюльпан', c=1},{name='Автоматизация', c=5},},create={{name='Пион', c=35},{name='Тюльпан', c=35},{name='Цифровой микроскоп', c=7},},createtm=30, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=80, level=12},
['Бархатцы']={name='Бархатцы', tm=14, buy=52, sell=105, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=240, level=40},
['Батат']={name='Батат', tm=7, buy=120, sell=131, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=1509, level=22},
['Бейонс']={name='Бейонс', tm=4, buy=115, sell=180, tp='Цветы', tp1='Семена' , agronom={{name='Лилия', c=1},{name='Роза', c=1},{name='Сертификат', c=1},},create={{name='Лилия', c=40},{name='Роза', c=40},{name='Монеты', c=20000},},createtm=22, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=90, level=11},
['Белладонна']={name='Белладонна', tm=10, buy=0, sell=130, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=60, level=30, vip=1},
['Белые грибы']={name='Белые грибы', tm=7, buy=20, sell=27, tp='Грибы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=46, level=4},
['Белый виноград']={name='Белый виноград', tm=10, buy=100, sell=110, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=80, level=2},
['Бойзенова ягода']={name='Бойзенова ягода', tm=12, buy=220, sell=420, tp='Фрукты', tp1='Семена' , agronom={{name='Малина', c=1},{name='Ежевика', c=1},{name='Автоматизация', c=5},},create={{name='Малина', c=80},{name='Ежевика', c=80},{name='Цифровой микроскоп', c=4},},createtm=12, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=1160, level=29},
['Брокколи']={name='Брокколи', tm=10, buy=60, sell=70, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=360, level=15},
['Брусника']={name='Брусника', tm=2, buy=185, sell=189, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=4440, level=12},
['Бузина черная']={name='Бузина черная', tm=27, buy=195, sell=260, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=953, level=33},
['Валериана']={name='Валериана', tm=12, buy=0, sell=210, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=70, level=27, vip=1},
['Ваниль']={name='Ваниль', tm=12, buy=120, sell=140, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=720, level=18},
['Василек']={name='Василек', tm=10, buy=125, sell=150, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=230, level=13},
['Вербена']={name='Вербена', tm=31, buy=225, sell=300, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=150, level=28},
['Верблюжья колючка']={name='Верблюжья колючка', tm=10, buy=35, sell=45, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=56, level=4},
['Вереск']={name='Вереск', tm=6, buy=95, sell=103, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=823, level=13},
['Вероника']={name='Вероника', tm=6, buy=130, sell=142, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=180, level=25},
['Виноград']={name='Виноград', tm=10, buy=105, sell=116, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=420, level=10},
['Водоросли комбу']={name='Водоросли комбу', tm=5, buy=750, sell=830, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=6000, level=10},
['Водяной бамбук']={name='Водяной бамбук', tm=12, buy=800, sell=920, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=7200, level=27},
['Водяной кресс']={name='Водяной кресс', tm=16, buy=1200, sell=1380, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=6900, level=23},
['Водяной перец']={name='Водяной перец', tm=20, buy=650, sell=840, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=5070, level=39},
['Волшебная малина']={name='Волшебная малина', tm=4, buy=95, sell=105, tp='Фрукты', tp1='Семена' ,  location='Волшебный остров', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Волшебный гриб']={name='Волшебный гриб', tm=8, buy=0, sell=95, tp='Другие семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=18, vip=1},
['Гвоздика']={name='Гвоздика', tm=11, buy=60, sell=73, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=80, level=13},
['Гербера']={name='Гербера', tm=2, buy=25, sell=32, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=320, level=36},
['Гиацинт']={name='Гиацинт', tm=5, buy=75, sell=83, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=70, level=9},
['Гладиолус']={name='Гладиолус', tm=20, buy=75, sell=100, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=180, level=32},
['Глубоководные грибы']={name='Глубоководные грибы', tm=17, buy=2550, sell=2822, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=10200, level=17},
['Голубика']={name='Голубика', tm=13, buy=140, sell=165, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=906, level=21},
['Голубой мак']={name='Голубой мак', tm=3, buy=50, sell=0, tp='Цветы', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=120, level=0},
['Горечавка']={name='Горечавка', tm=6, buy=80, sell=0, tp='Цветы', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=110, level=0},
['Горох']={name='Горох', tm=6, buy=110, sell=117, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=1467, level=20},
['Гортензия']={name='Гортензия', tm=12, buy=40, sell=86, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=240, level=38},
['Горчица']={name='Горчица', tm=12, buy=70, sell=85, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=257, level=11},
['Гречиха']={name='Гречиха', tm=5, buy=110, sell=118, tp='Травы', tp1='Семена' ,  location='Заповедник', diamond=0, platinum=0, gold=0, silver=0, bronze=1496, level=0},
['Груздь']={name='Груздь', tm=15, buy=125, sell=160, tp='Грибы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=105, level=4},
['Гуарана']={name='Гуарана', tm=16, buy=150, sell=175, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=1569, level=34},
['Джикама']={name='Джикама', tm=8, buy=205, sell=0, tp='Овощи', tp1='Семена' ,  location='Коралловый атолл', diamond=0, platinum=0, gold=0, silver=0, bronze=1450, level=0},
['Джут']={name='Джут', tm=17, buy=40, sell=80, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=273, level=29},
['Драконий когооть']={name='Драконий когооть', tm=9, buy=115, sell=135, tp='Другие семена', tp1='Семена' ,  location='Волшебный остров', diamond=0, platinum=0, gold=0, silver=0, bronze=220, level=0},
['Дыня']={name='Дыня', tm=48, buy=90, sell=145, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=150, level=20},
['Ежевика']={name='Ежевика', tm=9, buy=125, sell=135, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=1278, level=23},
['Женьшень']={name='Женьшень', tm=15, buy=130, sell=148, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=832, level=24},
['Звездная Кассиопея']={name='Звездная Кассиопея', tm=7, buy=0, sell=104, tp='Другие семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=15, vip=1},
['Звездная Медведица']={name='Звездная Медведица', tm=4, buy=0, sell=70, tp='Другие семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=18, vip=1},
['Звездная трава']={name='Звездная трава', tm=3, buy=0, sell=44, tp='Другие семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=21, vip=1},
['Звездный Жираф']={name='Звездный Жираф', tm=8, buy=0, sell=129, tp='Другие семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=15, vip=1},
['Звездный Рак']={name='Звездный Рак', tm=6, buy=0, sell=87, tp='Другие семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=18, vip=1},
['Звездчатка']={name='Звездчатка', tm=3, buy=45, sell=0, tp='Цветы', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=1400, level=0},
['Золотистый подсолнух']={name='Золотистый подсолнух', tm=9, buy=70, sell=85, tp='Травы', tp1='Семена' ,  location='Волшебный остров', diamond=0, platinum=0, gold=0, silver=0, bronze=630, level=0},
['Имбирь']={name='Имбирь', tm=14, buy=200, sell=230, tp='Овощи', tp1='Семена' ,  location='Тропический остров', diamond=0, platinum=0, gold=0, silver=0, bronze=1486, level=26},
['Ирис']={name='Ирис', tm=6, buy=60, sell=69, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=50, level=7},
['Кабачок']={name='Кабачок', tm=9, buy=21, sell=30, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=103, level=11},
['Кавбудек']={name='Кавбудек', tm=14, buy=0, sell=678, tp='Фрукты', tp1='Семена' , agronom={{name='Кавбуз', c=1},{name='Тыква', c=1},{name='Автоматизация', c=5},},create={{name='Кавбуз', c=3},{name='Тыква', c=60},{name='Резак семян', c=9},},createtm=48, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=6487, level=43},
['Кавбуз']={name='Кавбуз', tm=8, buy=255, sell=378, tp='Фрукты', tp1='Семена' , agronom={{name='Арбуз', c=1},{name='Тыква', c=1},{name='Автоматизация', c=5},},create={{name='Арбуз', c=40},{name='Тыква', c=40},{name='Цифровой микроскоп', c=6},},createtm=31, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=6007, level=41},
['Кактус']={name='Кактус', tm=17, buy=105, sell=141, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=95, level=10},
['Калла']={name='Калла', tm=5, buy=85, sell=97, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=120, level=16},
['Кампанула']={name='Кампанула', tm=3, buy=35, sell=90, tp='Цветы', tp1='Семена' , agronom={{name='Ландыш', c=1},{name='Колокольчик', c=1},{name='Автоматизация', c=10},},create={{name='Ландыш', c=20},{name='Колокольчик', c=20},{name='Цифровой микроскоп', c=5},},createtm=24, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=170, level=20},
['Кампернелли']={name='Кампернелли', tm=9, buy=150, sell=265, tp='Цветы', tp1='Семена' , agronom={{name='Нарцисс', c=1},{name='Гвоздика', c=1},{name='Автоматизация', c=5},},create={{name='Нарцисс', c=15},{name='Гвоздика', c=15},{name='Монеты', c=5000},},createtm=12, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=90, level=13},
['Камыш']={name='Камыш', tm=10, buy=600, sell=700, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=3360, level=14},
['Кандык']={name='Кандык', tm=20, buy=100, sell=0, tp='Цветы', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=160, level=0},
['Канна']={name='Канна', tm=16, buy=95, sell=157, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=230, level=39},
['Канна Ореол']={name='Канна Ореол', tm=11, buy=195, sell=400, tp='Цветы', tp1='Семена' , agronom={{name='Канна', c=1},{name='Ликаста', c=1},{name='Сертификат', c=1},},create={{name='Канна', c=85},{name='Ликаста', c=85},{name='Резак семян', c=8},},createtm=78, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=250, level=39},
['Капуста']={name='Капуста', tm=14, buy=35, sell=50, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=30, level=3},
['Карела']={name='Карела', tm=11, buy=120, sell=146, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=155, level=11},
['Картофель']={name='Картофель', tm=14, buy=40, sell=55, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=11, level=3},
['Киви']={name='Киви', tm=18, buy=105, sell=130, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=700, level=25},
['Клевер']={name='Клевер', tm=4, buy=15, sell=20, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=15, level=1},
['Клубника']={name='Клубника', tm=12, buy=75, sell=90, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=400, level=16},
['Колокольчик']={name='Колокольчик', tm=12, buy=20, sell=39, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=70, level=10},
['Колорадо']={name='Колорадо', tm=15, buy=140, sell=330, tp='Цветы', tp1='Семена' , agronom={{name='Гладиолус', c=1},{name='Астра', c=1},{name='Автоматизация', c=60},},create={{name='Гладиолус', c=25},{name='Астра', c=25},{name='Цифровой микроскоп', c=10},},createtm=56, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=190, level=32},
['Коралловый полип']={name='Коралловый полип', tm=0, buy=2600, sell=2941, tp='Морские семена', tp1='Семена' ,  location='Коралловый атолл', diamond=0, platinum=0, gold=0, silver=0, bronze=170, level=0},
['Кориандр']={name='Кориандр', tm=9, buy=170, sell=188, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=2040, level=27},
['Крапива']={name='Крапива', tm=4, buy=50, sell=59, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=1100, level=22},
['Красные водоросли']={name='Красные водоросли', tm=6, buy=900, sell=996, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=4800, level=8},
['Красный лотос']={name='Красный лотос', tm=11, buy=0, sell=0, tp='Морские семена', tp1='Семена' , agronom="", location='Остров динозавров', diamond=0, platinum=0, gold=0, silver=0, bronze=5236, level=0},
['Крылатые бобы']={name='Крылатые бобы', tm=8, buy=60, sell=0, tp='Другие семена', tp1='Семена' ,  location='Коралловый атолл', diamond=0, platinum=0, gold=0, silver=0, bronze=950, level=0},
['Кувшинка']={name='Кувшинка', tm=16, buy=620, sell=750, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=5270, level=34},
['Кукуруза']={name='Кукуруза', tm=20, buy=60, sell=80, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=60, level=5},
['Лаванда']={name='Лаванда', tm=12, buy=85, sell=122, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=310, level=50},
['Ландыш']={name='Ландыш', tm=4, buy=15, sell=20, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=160, level=20},
['Лантана']={name='Лантана', tm=13, buy=50, sell=75, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=110, level=17},
['Ледяная роза']={name='Ледяная роза', tm=24, buy=0, sell=2013, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=30, level=21},
['Лен']={name='Лен', tm=5, buy=160, sell=169, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=3072, level=24},
['Ликаста']={name='Ликаста', tm=15, buy=100, sell=132, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=120, level=19},
['Лилия']={name='Лилия', tm=6, buy=60, sell=68, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=40, level=5},
['Лиловая морковь']={name='Лиловая морковь', tm=4, buy=91, sell=150, tp='Овощи', tp1='Семена' , agronom={{name='Морковь', c=1},{name='Баклажан', c=1},{name='Автоматизация', c=5},},create={{name='Морковь', c=12},{name='Баклажан', c=12},{name='Цифровой микроскоп', c=6},},createtm=16, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=960, level=8},
['Лисички']={name='Лисички', tm=12, buy=100, sell=138, tp='Грибы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=1000, level=30},
['Лук']={name='Лук', tm=2, buy=10, sell=13, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=20, level=3},
['Лук душистый']={name='Лук душистый', tm=24, buy=54, sell=345, tp='Овощи', tp1='Семена' , agronom={{name='Лук', c=1},{name='Чеснок', c=1},{name='Автоматизация', c=10},},create={{name='Лук', c=3},{name='Чеснок', c=3},{name='Монеты', c=3000},},createtm=2, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=460, level=10},
['Лук скорода']={name='Лук скорода', tm=6, buy=160, sell=0, tp='Травы', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=1600, level=0},
['Лунный одуванчик']={name='Лунный одуванчик', tm=10, buy=0, sell=135, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=70, level=27, vip=1},
['Лунный цветок']={name='Лунный цветок', tm=14, buy=0, sell=470, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=60, level=24, vip=1},
['Люцерна']={name='Люцерна', tm=6, buy=25, sell=30, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=67, level=4},
['Мака перуанская']={name='Мака перуанская', tm=6, buy=160, sell=180, tp='Овощи', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=4267, level=0},
['Малина']={name='Малина', tm=9, buy=95, sell=105, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=1710, level=27},
['Мандрагора']={name='Мандрагора', tm=15, buy=0, sell=580, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=60, level=30, vip=1},
['Маниок']={name='Маниок', tm=19, buy=50, sell=100, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=347, level=33},
['Маракуйя']={name='Маракуйя', tm=23, buy=180, sell=205, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=2049, level=37},
['Марцишор']={name='Марцишор', tm=36, buy=2500, sell=2550, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=40, level=8},
['Миддлемист']={name='Миддлемист', tm=4, buy=275, sell=291, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=5050, level=45},
['Морковь']={name='Морковь', tm=8, buy=75, sell=84, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=300, level=9},
['Морошка']={name='Морошка', tm=6, buy=60, sell=90, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=720, level=18},
['Морская капуста']={name='Морская капуста', tm=2, buy=350, sell=382, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=5600, level=8},
['Морская репа']={name='Морская репа', tm=8, buy=1450, sell=1578, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=15},
['Морской анемон']={name='Морской анемон', tm=0, buy=3200, sell=0, tp='Морские семена', tp1='Семена' ,  location='Коралловый атолл', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Морской виноград']={name='Морской виноград', tm=6, buy=850, sell=950, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=9},
['Морской колокольчик']={name='Морской колокольчик', tm=12, buy=1220, sell=411, tp='Морские семена', tp1='Семена' , agronom={{name='Водяной кресс', c=1},{name='Колокольчик', c=1},{name='Автоматизация', c=5},},create={{name='Водяной кресс', c=5},{name='Колокольчик', c=30},{name='Монеты', c=40000},},createtm=8, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=28},
['Морской лук']={name='Морской лук', tm=6, buy=980, sell=1076, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=11},
['Морской мох']={name='Морской мох', tm=13, buy=1490, sell=1800, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=25},
['Мята']={name='Мята', tm=38, buy=126, sell=201, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=13},
['Нарцисс']={name='Нарцисс', tm=10, buy=90, sell=102, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=4},
['Нут']={name='Нут', tm=16, buy=50, sell=72, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=26},
['Овес']={name='Овес', tm=10, buy=110, sell=128, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=23},
['Огурдыня']={name='Огурдыня', tm=36, buy=115, sell=540, tp='Овощи', tp1='Семена' , agronom={{name='Огурцы', c=1},{name='Дыня', c=1},{name='Автоматизация', c=30},},create={{name='Огурцы', c=12},{name='Дыня', c=12},{name='Счетчик семян', c=5},},createtm=24, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=20},
['Огурцы']={name='Огурцы', tm=10, buy=25, sell=35, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=1},
['Океанская роза']={name='Океанская роза', tm=9, buy=1800, sell=1944, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=13},
['Олеандр']={name='Олеандр', tm=17, buy=82, sell=124, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=23},
['Опята']={name='Опята', tm=4, buy=20, sell=26, tp='Грибы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=10},
['Орхидея']={name='Орхидея', tm=7, buy=110, sell=126, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=14},
['Острый перец']={name='Острый перец', tm=17, buy=55, sell=75, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=12},
['Папирус']={name='Папирус', tm=12, buy=800, sell=920, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=27},
['Папоротник семенной']={name='Папоротник семенной', tm=4, buy=0, sell=150, tp='Травы', tp1='Семена' , agronom="", location='Остров динозавров', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Патиссон']={name='Патиссон', tm=11, buy=85, sell=105, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=36},
['Перец']={name='Перец', tm=9, buy=30, sell=40, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=9},
['Петрушка']={name='Петрушка', tm=21, buy=170, sell=215, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=21},
['Пион']={name='Пион', tm=18, buy=80, sell=98, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=12},
['Плюмерия']={name='Плюмерия', tm=18, buy=120, sell=170, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=27},
['Подберезовики']={name='Подберезовики', tm=24, buy=30, sell=65, tp='Грибы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=10},
['Подводная орхидея']={name='Подводная орхидея', tm=8, buy=1010, sell=378, tp='Морские семена', tp1='Семена' , agronom={{name='Красные водоросли', c=1},{name='Орхидея', c=1},{name='Автоматизация', c=5},},create={{name='Красные водоросли', c=10},{name='Орхидея', c=50},{name='Цифровой микроскоп', c=4},},createtm=12, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=39},
['Подосиновики']={name='Подосиновики', tm=32, buy=70, sell=105, tp='Грибы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=10},
['Подсолнух']={name='Подсолнух', tm=15, buy=70, sell=85, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=1},
['Полынь']={name='Полынь', tm=2, buy=65, sell=0, tp='Травы', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Полярный мох']={name='Полярный мох', tm=9, buy=0, sell=0, tp='Другие семена', tp1='Семена' ,  location='Северный полюс', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Помидор']={name='Помидор', tm=16, buy=20, sell=37, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=6},
['Прибрежная лилия']={name='Прибрежная лилия', tm=0, buy=1200, sell=0, tp='Морские семена', tp1='Семена' ,  location='Коралловый атолл', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Просо']={name='Просо', tm=15, buy=145, sell=171, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=19},
['Пшеница']={name='Пшеница', tm=12, buy=35, sell=48, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=1},
['Рапс']={name='Рапс', tm=20, buy=210, sell=268, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=29},
['Раффлезия Арнольда']={name='Раффлезия Арнольда', tm=12, buy=190, sell=0, tp='Цветы', tp1='Семена' ,  location='Коралловый атолл', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Рахис']={name='Рахис', tm=12, buy=80, sell=0, tp='Другие семена', tp1='Семена' ,  location='Коралловый атолл', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Ревень']={name='Ревень', tm=7, buy=140, sell=158, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=15},
['Редис']={name='Редис', tm=11, buy=135, sell=154, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=23},
['Редька']={name='Редька', tm=21, buy=240, sell=291, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=35},
['Репа']={name='Репа', tm=20, buy=180, sell=206, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=26},
['Рожь']={name='Рожь', tm=14, buy=125, sell=149, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=17},
['Роза']={name='Роза', tm=6, buy=55, sell=64, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=11},
['Розмарин']={name='Розмарин', tm=5, buy=117, sell=124, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=19},
['Романеско']={name='Романеско', tm=40, buy=95, sell=600, tp='Овощи', tp1='Семена' , agronom={{name='Капуста', c=1},{name='Брокколи', c=1},{name='Автоматизация', c=10},},create={{name='Капуста', c=30},{name='Брокколи', c=30},{name='Счетчик семян', c=6},},createtm=20, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=15},
['Ромашка']={name='Ромашка', tm=10, buy=25, sell=45, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=15},
['Рубиновая клубника']={name='Рубиновая клубника', tm=6, buy=75, sell=90, tp='Фрукты', tp1='Семена' ,  location='Волшебный остров', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Руккола']={name='Руккола', tm=3, buy=30, sell=40, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=32},
['Рыжики']={name='Рыжики', tm=18, buy=60, sell=129, tp='Грибы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=45},
['Салат']={name='Салат', tm=21, buy=180, sell=222, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=22},
['Сахарный тростник']={name='Сахарный тростник', tm=3, buy=55, sell=60, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=24},
['Свекла']={name='Свекла', tm=7, buy=55, sell=65, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=3},
['Светильник Джекаы']={name='Светильник Джекаы', tm=24, buy=0, sell=104, tp='Другие семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=15, vip=1},
['Сельдерей']={name='Сельдерей', tm=28, buy=50, sell=115, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=38},
['Сельтус']={name='Сельтус', tm=16, buy=230, sell=495, tp='Овощи', tp1='Семена' , agronom={{name='Салат', c=1},{name='Сельдерей', c=1},{name='Автоматизация', c=10},},create={{name='Салат', c=55},{name='Сельдерей', c=55},{name='Резак семян', c=12},},createtm=55, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=38},
['Сладкая болотница']={name='Сладкая болотница', tm=8, buy=1100, sell=1170, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=43},
['Сладкий шоколадный перец']={name='Сладкий шоколадный перец', tm=7, buy=85, sell=190, tp='Овощи', tp1='Семена' , agronom={{name='Перец', c=1},{name='Острый перец', c=1},{name='Автоматизация', c=10},},create={{name='Перец', c=25},{name='Острый перец', c=25},{name='Пробирки', c=9},},createtm=24, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=12},
['Смолевка']={name='Смолевка', tm=4, buy=0, sell=180, tp='Цветы', tp1='Семена' , agronom="", location='Остров динозавров', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Соя']={name='Соя', tm=12, buy=120, sell=145, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=55},
['Спаржа']={name='Спаржа', tm=5, buy=45, sell=59, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=60},
['Сыроежки']={name='Сыроежки', tm=20, buy=65, sell=108, tp='Грибы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=16},
['Тайберри']={name='Тайберри', tm=7, buy=220, sell=310, tp='Фрукты', tp1='Семена' , agronom={{name='Ежевика', c=1},{name='Малина', c=1},{name='Автоматизация', c=50},},create={{name='Ежевика', c=20},{name='Малина', c=20},{name='Влагомер почвы', c=9},},createtm=48, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=27},
['Таро']={name='Таро', tm=8, buy=1100, sell=1170, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=43},
['Тигровая лилия']={name='Тигровая лилия', tm=3, buy=0, sell=80, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=24, vip=1},
['Тмин']={name='Тмин', tm=8, buy=210, sell=235, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=20},
['Томтато']={name='Томтато', tm=20, buy=60, sell=300, tp='Овощи', tp1='Семена' , agronom={{name='Помидор', c=1},{name='Картофель', c=1},{name='Автоматизация', c=5},},create={{name='Помидор', c=50},{name='Картофель', c=50},{name='Монеты', c=10000},},createtm=5, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=10},
['Топинамбур']={name='Топинамбур', tm=5, buy=80, sell=95, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=25},
['Тритикале']={name='Тритикале', tm=9, buy=160, sell=230, tp='Травы', tp1='Семена' , agronom={{name='Пшеница', c=1},{name='Рожь', c=1},{name='Автоматизация', c=5},},create={{name='Пшеница', c=18},{name='Рожь', c=18},{name='Монеты', c=7500},},createtm=16, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=17},
['Тыква']={name='Тыква', tm=24, buy=125, sell=150, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=31},
['Тюльпан']={name='Тюльпан', tm=3, buy=10, sell=14, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=2},
['Укроп']={name='Укроп', tm=19, buy=140, sell=180, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=16},
['Фасоль']={name='Фасоль', tm=36, buy=84, sell=158, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=11},
['Фиалка']={name='Фиалка', tm=10, buy=32, sell=46, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=22},
['Фиалка пренебреженная']={name='Фиалка пренебреженная', tm=16, buy=0, sell=650, tp='Цветы', tp1='Семена' , agronom="", location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=52},
['Физалис']={name='Физалис', tm=5, buy=105, sell=116, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=10},
['Флокс']={name='Флокс', tm=10, buy=140, sell=155, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=21},
['Фризо']={name='Фризо', tm=16, buy=115, sell=240, tp='Цветы', tp1='Семена' , agronom={{name='Лилия', c=1},{name='Азалия', c=1},{name='Автоматизация', c=10},},create={{name='Лилия', c=40},{name='Азалия', c=40},{name='Промышленный респиратор', c=5},},createtm=50, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=24},
['Хлопок']={name='Хлопок', tm=24, buy=45, sell=60, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=15},
['Хмель']={name='Хмель', tm=16, buy=83, sell=92, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=7},
['Хохлатка']={name='Хохлатка', tm=5, buy=20, sell=0, tp='Цветы', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Хризантема']={name='Хризантема', tm=7, buy=15, sell=22, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=18},
['Хризантема сибирская']={name='Хризантема сибирская', tm=8, buy=40, sell=145, tp='Цветы', tp1='Семена' , agronom={{name='Хризантема', c=1},{name='Ромашка', c=1},{name='Автоматизация', c=40},},create={{name='Хризантема', c=15},{name='Ромашка', c=15},{name='Резак семян', c=6},},createtm=32, location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=18},
['Хрустальный цветок']={name='Хрустальный цветок', tm=5, buy=0, sell=247, tp='Цветы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=24, vip=1},
['Цветная капуста']={name='Цветная капуста', tm=10, buy=86, sell=102, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=28},
['Цукини']={name='Цукини', tm=8, buy=120, sell=137, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=28},
['Чайот']={name='Чайот', tm=12, buy=205, sell=242, tp='Овощи', tp1='Семена' ,  location='Коралловый атолл', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Чашка русалки']={name='Чашка русалки', tm=7, buy=1450, sell=1623, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=10},
['Черная малина']={name='Черная малина', tm=7, buy=70, sell=84, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=70},
['Черника']={name='Черника', tm=3, buy=85, sell=91, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=19},
['Черный коралл']={name='Черный коралл', tm=0, buy=1500, sell=0, tp='Морские семена', tp1='Семена' ,  location='Коралловый атолл', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Черный рис']={name='Черный рис', tm=20, buy=650, sell=840, tp='Морские семена', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=39},
['Черри']={name='Черри', tm=25, buy=65, sell=115, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=30},
['Чеснок']={name='Чеснок', tm=31, buy=44, sell=93, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=10},
['Чечевица']={name='Чечевица', tm=22, buy=60, sell=86, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=12},
['Шампиньоны']={name='Шампиньоны', tm=9, buy=250, sell=273, tp='Грибы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=40},
['Шафран']={name='Шафран', tm=16, buy=236, sell=280, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=29},
['Шпинат']={name='Шпинат', tm=17, buy=98, sell=119, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=14},
['Щавель']={name='Щавель', tm=9, buy=216, sell=235, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=32},
['Эдельвейс']={name='Эдельвейс', tm=16, buy=140, sell=0, tp='Цветы', tp1='Семена' ,  location='Высокогорье', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Ярета']={name='Ярета', tm=7, buy=0, sell=190, tp='Травы', tp1='Семена' , agronom="", location='Остров динозавров', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Ячмень']={name='Ячмень', tm=7, buy=92, sell=104, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=15},
['Кардамон']={name='Кардамон', tm=23, buy=170, sell=240, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=16},
['Лук-порей']={name='Лук-порей', tm=0.5, buy=18, sell=21, tp='Травы', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=1},
['Чабрец']={name='Чабрец', tm=6, buy=0, sell=0, tp='Травы', tp1='Семена' ,  location='Цветущий сад', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Шалфей']={name='Шалфей', tm=2, buy=0, sell=0, tp='Травы', tp1='Семена' ,  location='Цветущий сад', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Куркума']={name='Куркума', tm=15, buy=0, sell=0, tp='Овощи', tp1='Семена' ,  location='Цветущий сад', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=0},
['Корнишоны']={name='Корнишоны', tm=0.0167
, buy=5, sell=6, tp='Овощи', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=1},
['Земляника']={name='Земляника', tm=0.167
, buy=12, sell=14, tp='Фрукты', tp1='Семена' ,  location='', diamond=0, platinum=0, gold=0, silver=0, bronze=0, level=1},

}

